
% [Sensitivity,Specificity,Accuracy,BA, Precision,F1]
% Recog.Feature.Long(1).CNN.PrecisionC1,Recog.Feature.Long(1).CNN.F1C1

[Recog.Feature.Long(1).CNN.SensitivityC1,Recog.Feature.Long(1).CNN.SpecificityC1,Recog.Feature.Long(1).CNN.AccuracyC1,Recog.Feature.Long(1).CNN.BAC1,Recog.Feature.Long(1).CNN.PrecisionC1,Recog.Feature.Long(1).CNN.F1C1] =  CM_Sen_Spec_binary_calc(Recog.Feature.Long(1).Label,Recog.Feature.Long(1).CNN.Prediction)
[Recog.Feature.Long(5).CNN.SensitivityC1,Recog.Feature.Long(5).CNN.SpecificityC1,Recog.Feature.Long(5).CNN.AccuracyC1,Recog.Feature.Long(5).CNN.BAC1,Recog.Feature.Long(5).CNN.PrecisionC1,Recog.Feature.Long(5).CNN.F1C1] =  CM_Sen_Spec_binary_calc(Recog.Feature.Long(5).Label,Recog.Feature.Long(5).CNN.Prediction)
[Recog.Feature.Long(12).CNN.SensitivityC1,Recog.Feature.Long(12).CNN.SpecificityC1,Recog.Feature.Long(12).CNN.AccuracyC1,Recog.Feature.Long(12).CNN.BAC1,Recog.Feature.Long(12).CNN.PrecisionC1,Recog.Feature.Long(12).CNN.F1C1] =  CM_Sen_Spec_binary_calc(Recog.Feature.Long(12).Label,Recog.Feature.Long(12).CNN.Prediction)
[Recog.Feature.Mean(5).CNN.SensitivityC1,Recog.Feature.Mean(5).CNN.SpecificityC1,Recog.Feature.Mean(5).CNN.AccuracyC1,Recog.Feature.Mean(5).CNN.BAC1,Recog.Feature.Mean(5).CNN.PrecisionC1,Recog.Feature.Mean(5).CNN.F1C1] =  CM_Sen_Spec_binary_calc(Recog.Feature.Mean(5).Label,Recog.Feature.Mean(5).CNN.Prediction)
[Recog.Feature.Mean(12).CNN.SensitivityC1,Recog.Feature.Mean(12).CNN.SpecificityC1,Recog.Feature.Mean(12).CNN.AccuracyC1,Recog.Feature.Mean(12).CNN.BAC1,Recog.Feature.Mean(12).CNN.PrecisionC1,Recog.Feature.Mean(12).CNN.F1C1] =  CM_Sen_Spec_binary_calc(Recog.Feature.Mean(12).Label,Recog.Feature.Mean(12).CNN.Prediction)


[Recog.Feature.Long(1).MLP.SensitivityC1,Recog.Feature.Long(1).MLP.SpecificityC1,Recog.Feature.Long(1).MLP.AccuracyC1,Recog.Feature.Long(1).MLP.BAC1,Recog.Feature.Long(1).MLP.PrecisionC1,Recog.Feature.Long(1).MLP.F1C1] =  CM_Sen_Spec_binary_calc(Recog.Feature.Long(1).Label,Recog.Feature.Long(1).MLP.Prediction)
[Recog.Feature.Long(5).MLP.SensitivityC1,Recog.Feature.Long(5).MLP.SpecificityC1,Recog.Feature.Long(5).MLP.AccuracyC1,Recog.Feature.Long(5).MLP.BAC1,Recog.Feature.Long(5).MLP.PrecisionC1,Recog.Feature.Long(5).MLP.F1C1] =  CM_Sen_Spec_binary_calc(Recog.Feature.Long(5).Label,Recog.Feature.Long(5).MLP.Prediction)
[Recog.Feature.Long(12).MLP.SensitivityC1,Recog.Feature.Long(12).MLP.SpecificityC1,Recog.Feature.Long(12).MLP.AccuracyC1,Recog.Feature.Long(12).MLP.BAC1,Recog.Feature.Long(12).MLP.PrecisionC1,Recog.Feature.Long(12).MLP.F1C1] =  CM_Sen_Spec_binary_calc(Recog.Feature.Long(12).Label,Recog.Feature.Long(12).MLP.Prediction)
[Recog.Feature.Mean(5).MLP.SensitivityC1,Recog.Feature.Mean(5).MLP.SpecificityC1,Recog.Feature.Mean(5).MLP.AccuracyC1,Recog.Feature.Mean(5).MLP.BAC1,Recog.Feature.Mean(5).MLP.PrecisionC1,Recog.Feature.Mean(5).MLP.F1C1] =  CM_Sen_Spec_binary_calc(Recog.Feature.Mean(5).Label,Recog.Feature.Mean(5).MLP.Prediction)
[Recog.Feature.Mean(12).MLP.SensitivityC1,Recog.Feature.Mean(12).MLP.SpecificityC1,Recog.Feature.Mean(12).MLP.AccuracyC1,Recog.Feature.Mean(12).MLP.BAC1,Recog.Feature.Mean(12).MLP.PrecisionC1,Recog.Feature.Mean(12).MLP.F1C1] =  CM_Sen_Spec_binary_calc(Recog.Feature.Mean(12).Label,Recog.Feature.Mean(12).MLP.Prediction)


[Recog.Feature.Long(1).LSTM.SensitivityC1,Recog.Feature.Long(1).LSTM.SpecificityC1,Recog.Feature.Long(1).LSTM.AccuracyC1,Recog.Feature.Long(1).LSTM.BAC1,Recog.Feature.Long(1).LSTM.PrecisionC1,Recog.Feature.Long(1).LSTM.F1C1] =  CM_Sen_Spec_binary_calc(Recog.Feature.Long(1).Label,Recog.Feature.Long(1).LSTM.Prediction)
[Recog.Feature.Long(5).LSTM.SensitivityC1,Recog.Feature.Long(5).LSTM.SpecificityC1,Recog.Feature.Long(5).LSTM.AccuracyC1,Recog.Feature.Long(5).LSTM.BAC1,Recog.Feature.Long(5).LSTM.PrecisionC1,Recog.Feature.Long(5).LSTM.F1C1] =  CM_Sen_Spec_binary_calc(Recog.Feature.Long(5).Label,Recog.Feature.Long(5).LSTM.Prediction)
[Recog.Feature.Long(12).LSTM.SensitivityC1,Recog.Feature.Long(12).LSTM.SpecificityC1,Recog.Feature.Long(12).LSTM.AccuracyC1,Recog.Feature.Long(12).LSTM.BAC1,Recog.Feature.Long(12).LSTM.PrecisionC1,Recog.Feature.Long(12).LSTM.F1C1] =  CM_Sen_Spec_binary_calc(Recog.Feature.Long(12).Label,Recog.Feature.Long(12).LSTM.Prediction)
[Recog.Feature.Mean(5).LSTM.SensitivityC1,Recog.Feature.Mean(5).LSTM.SpecificityC1,Recog.Feature.Mean(5).LSTM.AccuracyC1,Recog.Feature.Mean(5).LSTM.BAC1,Recog.Feature.Mean(5).LSTM.PrecisionC1,Recog.Feature.Mean(5).LSTM.F1C1] =  CM_Sen_Spec_binary_calc(Recog.Feature.Mean(5).Label,Recog.Feature.Mean(5).LSTM.Prediction)
[Recog.Feature.Mean(12).LSTM.SensitivityC1,Recog.Feature.Mean(12).LSTM.SpecificityC1,Recog.Feature.Mean(12).LSTM.AccuracyC1,Recog.Feature.Mean(12).LSTM.BAC1,Recog.Feature.Mean(12).LSTM.PrecisionC1,Recog.Feature.Mean(12).LSTM.F1C1] =  CM_Sen_Spec_binary_calc(Recog.Feature.Mean(12).Label,Recog.Feature.Mean(12).LSTM.Prediction)


[Recog.Raw.Long(1).CNN.SensitivityC1,Recog.Raw.Long(1).CNN.SpecificityC1,Recog.Raw.Long(1).CNN.AccuracyC1,Recog.Raw.Long(1).CNN.BAC1,Recog.Raw.Long(1).CNN.PrecisionC1,Recog.Raw.Long(1).CNN.F1C1] =  CM_Sen_Spec_binary_calc(Recog.Raw.Long(1).Label,Recog.Raw.Long(1).CNN.Prediction)
[Recog.Raw.Long(5).CNN.SensitivityC1,Recog.Raw.Long(5).CNN.SpecificityC1,Recog.Raw.Long(5).CNN.AccuracyC1,Recog.Raw.Long(5).CNN.BAC1,Recog.Raw.Long(5).CNN.PrecisionC1,Recog.Raw.Long(5).CNN.F1C1] =  CM_Sen_Spec_binary_calc(Recog.Raw.Long(5).Label,Recog.Raw.Long(5).CNN.Prediction)
[Recog.Raw.Long(12).CNN.SensitivityC1,Recog.Raw.Long(12).CNN.SpecificityC1,Recog.Raw.Long(12).CNN.AccuracyC1,Recog.Raw.Long(12).CNN.BAC1,Recog.Raw.Long(12).CNN.PrecisionC1,Recog.Raw.Long(12).CNN.F1C1] =  CM_Sen_Spec_binary_calc(Recog.Raw.Long(12).Label,Recog.Raw.Long(12).CNN.Prediction)
[Recog.Raw.Mean(5).CNN.SensitivityC1,Recog.Raw.Mean(5).CNN.SpecificityC1,Recog.Raw.Mean(5).CNN.AccuracyC1,Recog.Raw.Mean(5).CNN.BAC1,Recog.Raw.Mean(5).CNN.PrecisionC1,Recog.Raw.Mean(5).CNN.F1C1] =  CM_Sen_Spec_binary_calc(Recog.Raw.Mean(5).Label,Recog.Raw.Mean(5).CNN.Prediction)
[Recog.Raw.Mean(12).CNN.SensitivityC1,Recog.Raw.Mean(12).CNN.SpecificityC1,Recog.Raw.Mean(12).CNN.AccuracyC1,Recog.Raw.Mean(12).CNN.BAC1,Recog.Raw.Mean(12).CNN.PrecisionC1,Recog.Raw.Mean(12).CNN.F1C1] =  CM_Sen_Spec_binary_calc(Recog.Raw.Mean(12).Label,Recog.Raw.Mean(12).CNN.Prediction)


[Recog.Raw.Long(1).MLP.SensitivityC1,Recog.Raw.Long(1).MLP.SpecificityC1,Recog.Raw.Long(1).MLP.AccuracyC1,Recog.Raw.Long(1).MLP.BAC1,Recog.Raw.Long(1).MLP.PrecisionC1,Recog.Raw.Long(1).MLP.F1C1] =  CM_Sen_Spec_binary_calc(Recog.Raw.Long(1).Label,Recog.Raw.Long(1).MLP.Prediction)
[Recog.Raw.Long(5).MLP.SensitivityC1,Recog.Raw.Long(5).MLP.SpecificityC1,Recog.Raw.Long(5).MLP.AccuracyC1,Recog.Raw.Long(5).MLP.BAC1,Recog.Raw.Long(5).MLP.PrecisionC1,Recog.Raw.Long(5).MLP.F1C1] =  CM_Sen_Spec_binary_calc(Recog.Raw.Long(5).Label,Recog.Raw.Long(5).MLP.Prediction)
[Recog.Raw.Long(12).MLP.SensitivityC1,Recog.Raw.Long(12).MLP.SpecificityC1,Recog.Raw.Long(12).MLP.AccuracyC1,Recog.Raw.Long(12).MLP.BAC1,Recog.Raw.Long(12).MLP.PrecisionC1,Recog.Raw.Long(12).MLP.F1C1] =  CM_Sen_Spec_binary_calc(Recog.Raw.Long(12).Label,Recog.Raw.Long(12).MLP.Prediction)
[Recog.Raw.Mean(5).MLP.SensitivityC1,Recog.Raw.Mean(5).MLP.SpecificityC1,Recog.Raw.Mean(5).MLP.AccuracyC1,Recog.Raw.Mean(5).MLP.BAC1,Recog.Raw.Mean(5).MLP.PrecisionC1,Recog.Raw.Mean(5).MLP.F1C1] =  CM_Sen_Spec_binary_calc(Recog.Raw.Mean(5).Label,Recog.Raw.Mean(5).MLP.Prediction)
[Recog.Raw.Mean(12).MLP.SensitivityC1,Recog.Raw.Mean(12).MLP.SpecificityC1,Recog.Raw.Mean(12).MLP.AccuracyC1,Recog.Raw.Mean(12).MLP.BAC1,Recog.Raw.Mean(12).MLP.PrecisionC1,Recog.Raw.Mean(12).MLP.F1C1] =  CM_Sen_Spec_binary_calc(Recog.Raw.Mean(12).Label,Recog.Raw.Mean(12).MLP.Prediction)


[Recog.Raw.Long(1).LSTM.SensitivityC1,Recog.Raw.Long(1).LSTM.SpecificityC1,Recog.Raw.Long(1).LSTM.AccuracyC1,Recog.Raw.Long(1).LSTM.BAC1,Recog.Raw.Long(1).LSTM.PrecisionC1,Recog.Raw.Long(1).LSTM.F1C1] =  CM_Sen_Spec_binary_calc(Recog.Raw.Long(1).Label,Recog.Raw.Long(1).LSTM.Prediction)
[Recog.Raw.Long(5).LSTM.SensitivityC1,Recog.Raw.Long(5).LSTM.SpecificityC1,Recog.Raw.Long(5).LSTM.AccuracyC1,Recog.Raw.Long(5).LSTM.BAC1,Recog.Raw.Long(5).LSTM.PrecisionC1,Recog.Raw.Long(5).LSTM.F1C1] =  CM_Sen_Spec_binary_calc(Recog.Raw.Long(5).Label,Recog.Raw.Long(5).LSTM.Prediction)
% [Recog.Raw.Long(12).LSTM.SensitivityC1,Recog.Raw.Long(12).LSTM.SpecificityC1,Recog.Raw.Long(12).LSTM.AccuracyC1,Recog.Raw.Long(12).LSTM.BAC1,Recog.Raw.Long(12).LSTM.PrecisionC1,Recog.Raw.Long(12).LSTM.F1C1] =  CM_Sen_Spec_binary_calc(Recog.Raw.Long(12).Label,Recog.Raw.Long(12).LSTM.Prediction)
[Recog.Raw.Mean(5).LSTM.SensitivityC1,Recog.Raw.Mean(5).LSTM.SpecificityC1,Recog.Raw.Mean(5).LSTM.AccuracyC1,Recog.Raw.Mean(5).LSTM.BAC1,Recog.Raw.Mean(5).LSTM.PrecisionC1,Recog.Raw.Mean(5).LSTM.F1C1] =  CM_Sen_Spec_binary_calc(Recog.Raw.Mean(5).Label,Recog.Raw.Mean(5).LSTM.Prediction)
[Recog.Raw.Mean(12).LSTM.SensitivityC1,Recog.Raw.Mean(12).LSTM.SpecificityC1,Recog.Raw.Mean(12).LSTM.AccuracyC1,Recog.Raw.Mean(12).LSTM.BAC1,Recog.Raw.Mean(12).LSTM.PrecisionC1,Recog.Raw.Mean(12).LSTM.F1C1] =  CM_Sen_Spec_binary_calc(Recog.Raw.Mean(12).Label,Recog.Raw.Mean(12).LSTM.Prediction)

