
class =1

[Triclass.Feature.Long(1).CNN.AccuracyC1,Triclass.Feature.Long(1).CNN.TPRC1,Triclass.Feature.Long(1).CNN.PrecisionC1,Triclass.Feature.Long(1).CNN.RecallC1,Triclass.Feature.Long(1).CNN.F1C1] =  CM_Sen_Spec_trinary_calc(Triclass.Feature.Long(1).Label,Triclass.Feature.Long(1).CNN.Prediction,class)
[Triclass.Feature.Long(5).CNN.AccuracyC1,Triclass.Feature.Long(5).CNN.TPRC1,Triclass.Feature.Long(5).CNN.PrecisionC1,Triclass.Feature.Long(5).CNN.RecallC1,Triclass.Feature.Long(5).CNN.F1C1] =  CM_Sen_Spec_trinary_calc(Triclass.Feature.Long(5).Label,Triclass.Feature.Long(5).CNN.Prediction,class)
[Triclass.Feature.Long(12).CNN.AccuracyC1,Triclass.Feature.Long(12).CNN.TPRC1,Triclass.Feature.Long(12).CNN.PrecisionC1,Triclass.Feature.Long(12).CNN.RecallC1,Triclass.Feature.Long(12).CNN.F1C1] =  CM_Sen_Spec_trinary_calc(Triclass.Feature.Long(12).Label,Triclass.Feature.Long(12).CNN.Prediction,class)
[Triclass.Feature.Mean(5).CNN.AccuracyC1,Triclass.Feature.Mean(5).CNN.TPRC1,Triclass.Feature.Mean(5).CNN.PrecisionC1,Triclass.Feature.Mean(5).CNN.RecallC1,Triclass.Feature.Mean(5).CNN.F1C1] =  CM_Sen_Spec_trinary_calc(Triclass.Feature.Mean(5).Label,Triclass.Feature.Mean(5).CNN.Prediction,class)
[Triclass.Feature.Mean(12).CNN.AccuracyC1,Triclass.Feature.Mean(12).CNN.TPRC1,Triclass.Feature.Mean(12).CNN.PrecisionC1,Triclass.Feature.Mean(12).CNN.RecallC1,Triclass.Feature.Mean(12).CNN.F1C1] =  CM_Sen_Spec_trinary_calc(Triclass.Feature.Mean(12).Label,Triclass.Feature.Mean(12).CNN.Prediction,class)

[Triclass.Feature.Long(1).MLP.AccuracyC1,Triclass.Feature.Long(1).MLP.TPRC1,Triclass.Feature.Long(1).MLP.PrecisionC1,Triclass.Feature.Long(1).MLP.RecallC1,Triclass.Feature.Long(1).MLP.F1C1] =  CM_Sen_Spec_trinary_calc(Triclass.Feature.Long(1).Label,Triclass.Feature.Long(1).MLP.Prediction,class)
[Triclass.Feature.Long(5).MLP.AccuracyC1,Triclass.Feature.Long(5).MLP.TPRC1,Triclass.Feature.Long(5).MLP.PrecisionC1,Triclass.Feature.Long(5).MLP.RecallC1,Triclass.Feature.Long(5).MLP.F1C1] =  CM_Sen_Spec_trinary_calc(Triclass.Feature.Long(5).Label,Triclass.Feature.Long(5).MLP.Prediction,class)
[Triclass.Feature.Long(12).MLP.AccuracyC1,Triclass.Feature.Long(12).MLP.TPRC1,Triclass.Feature.Long(12).MLP.PrecisionC1,Triclass.Feature.Long(12).MLP.RecallC1,Triclass.Feature.Long(12).MLP.F1C1] =  CM_Sen_Spec_trinary_calc(Triclass.Feature.Long(12).Label,Triclass.Feature.Long(12).MLP.Prediction,class)
[Triclass.Feature.Mean(5).MLP.AccuracyC1,Triclass.Feature.Mean(5).MLP.TPRC1,Triclass.Feature.Mean(5).MLP.PrecisionC1,Triclass.Feature.Mean(5).MLP.RecallC1,Triclass.Feature.Mean(5).MLP.F1C1] =  CM_Sen_Spec_trinary_calc(Triclass.Feature.Mean(5).Label,Triclass.Feature.Mean(5).MLP.Prediction,class)
[Triclass.Feature.Mean(12).MLP.AccuracyC1,Triclass.Feature.Mean(12).MLP.TPRC1,Triclass.Feature.Mean(12).MLP.PrecisionC1,Triclass.Feature.Mean(12).MLP.RecallC1,Triclass.Feature.Mean(12).MLP.F1C1] =  CM_Sen_Spec_trinary_calc(Triclass.Feature.Mean(12).Label,Triclass.Feature.Mean(12).MLP.Prediction,class)

[Triclass.Feature.Long(1).LSTM.AccuracyC1,Triclass.Feature.Long(1).LSTM.TPRC1,Triclass.Feature.Long(1).LSTM.PrecisionC1,Triclass.Feature.Long(1).LSTM.RecallC1,Triclass.Feature.Long(1).LSTM.F1C1] =  CM_Sen_Spec_trinary_calc(Triclass.Feature.Long(1).Label,Triclass.Feature.Long(1).LSTM.Prediction,class)
[Triclass.Feature.Long(5).LSTM.AccuracyC1,Triclass.Feature.Long(5).LSTM.TPRC1,Triclass.Feature.Long(5).LSTM.PrecisionC1,Triclass.Feature.Long(5).LSTM.RecallC1,Triclass.Feature.Long(5).LSTM.F1C1] =  CM_Sen_Spec_trinary_calc(Triclass.Feature.Long(5).Label,Triclass.Feature.Long(5).LSTM.Prediction,class)
[Triclass.Feature.Long(12).LSTM.AccuracyC1,Triclass.Feature.Long(12).LSTM.TPRC1,Triclass.Feature.Long(12).LSTM.PrecisionC1,Triclass.Feature.Long(12).LSTM.RecallC1,Triclass.Feature.Long(12).LSTM.F1C1] =  CM_Sen_Spec_trinary_calc(Triclass.Feature.Long(12).Label,Triclass.Feature.Long(12).LSTM.Prediction,class)
[Triclass.Feature.Mean(5).LSTM.AccuracyC1,Triclass.Feature.Mean(5).LSTM.TPRC1,Triclass.Feature.Mean(5).LSTM.PrecisionC1,Triclass.Feature.Mean(5).LSTM.RecallC1,Triclass.Feature.Mean(5).LSTM.F1C1] =  CM_Sen_Spec_trinary_calc(Triclass.Feature.Mean(5).Label,Triclass.Feature.Mean(5).LSTM.Prediction,class)
[Triclass.Feature.Mean(12).LSTM.AccuracyC1,Triclass.Feature.Mean(12).LSTM.TPRC1,Triclass.Feature.Mean(12).LSTM.PrecisionC1,Triclass.Feature.Mean(12).LSTM.RecallC1,Triclass.Feature.Mean(12).LSTM.F1C1] =  CM_Sen_Spec_trinary_calc(Triclass.Feature.Mean(12).Label,Triclass.Feature.Mean(12).LSTM.Prediction,class)

class =2

[Triclass.Feature.Long(1).CNN.AccuracyC2,Triclass.Feature.Long(1).CNN.TPRC2,Triclass.Feature.Long(1).CNN.PrecisionC2,Triclass.Feature.Long(1).CNN.RecallC2,Triclass.Feature.Long(1).CNN.F1C2] =  CM_Sen_Spec_trinary_calc(Triclass.Feature.Long(1).Label,Triclass.Feature.Long(1).CNN.Prediction,class)
[Triclass.Feature.Long(5).CNN.AccuracyC2,Triclass.Feature.Long(5).CNN.TPRC2,Triclass.Feature.Long(5).CNN.PrecisionC2,Triclass.Feature.Long(5).CNN.RecallC2,Triclass.Feature.Long(5).CNN.F1C2] =  CM_Sen_Spec_trinary_calc(Triclass.Feature.Long(5).Label,Triclass.Feature.Long(5).CNN.Prediction,class)
[Triclass.Feature.Long(12).CNN.AccuracyC2,Triclass.Feature.Long(12).CNN.TPRC2,Triclass.Feature.Long(12).CNN.PrecisionC2,Triclass.Feature.Long(12).CNN.RecallC2,Triclass.Feature.Long(12).CNN.F1C2] =  CM_Sen_Spec_trinary_calc(Triclass.Feature.Long(12).Label,Triclass.Feature.Long(12).CNN.Prediction,class)
[Triclass.Feature.Mean(5).CNN.AccuracyC2,Triclass.Feature.Mean(5).CNN.TPRC2,Triclass.Feature.Mean(5).CNN.PrecisionC2,Triclass.Feature.Mean(5).CNN.RecallC2,Triclass.Feature.Mean(5).CNN.F1C2] =  CM_Sen_Spec_trinary_calc(Triclass.Feature.Mean(5).Label,Triclass.Feature.Mean(5).CNN.Prediction,class)
[Triclass.Feature.Mean(12).CNN.AccuracyC2,Triclass.Feature.Mean(12).CNN.TPRC2,Triclass.Feature.Mean(12).CNN.PrecisionC2,Triclass.Feature.Mean(12).CNN.RecallC2,Triclass.Feature.Mean(12).CNN.F1C2] =  CM_Sen_Spec_trinary_calc(Triclass.Feature.Mean(12).Label,Triclass.Feature.Mean(12).CNN.Prediction,class)

[Triclass.Feature.Long(1).MLP.AccuracyC2,Triclass.Feature.Long(1).MLP.TPRC2,Triclass.Feature.Long(1).MLP.PrecisionC2,Triclass.Feature.Long(1).MLP.RecallC2,Triclass.Feature.Long(1).MLP.F1C2] =  CM_Sen_Spec_trinary_calc(Triclass.Feature.Long(1).Label,Triclass.Feature.Long(1).MLP.Prediction,class)
[Triclass.Feature.Long(5).MLP.AccuracyC2,Triclass.Feature.Long(5).MLP.TPRC2,Triclass.Feature.Long(5).MLP.PrecisionC2,Triclass.Feature.Long(5).MLP.RecallC2,Triclass.Feature.Long(5).MLP.F1C2] =  CM_Sen_Spec_trinary_calc(Triclass.Feature.Long(5).Label,Triclass.Feature.Long(5).MLP.Prediction,class)
[Triclass.Feature.Long(12).MLP.AccuracyC2,Triclass.Feature.Long(12).MLP.TPRC2,Triclass.Feature.Long(12).MLP.PrecisionC2,Triclass.Feature.Long(12).MLP.RecallC2,Triclass.Feature.Long(12).MLP.F1C2] =  CM_Sen_Spec_trinary_calc(Triclass.Feature.Long(12).Label,Triclass.Feature.Long(12).MLP.Prediction,class)
[Triclass.Feature.Mean(5).MLP.AccuracyC2,Triclass.Feature.Mean(5).MLP.TPRC2,Triclass.Feature.Mean(5).MLP.PrecisionC2,Triclass.Feature.Mean(5).MLP.RecallC2,Triclass.Feature.Mean(5).MLP.F1C2] =  CM_Sen_Spec_trinary_calc(Triclass.Feature.Mean(5).Label,Triclass.Feature.Mean(5).MLP.Prediction,class)
[Triclass.Feature.Mean(12).MLP.AccuracyC2,Triclass.Feature.Mean(12).MLP.TPRC2,Triclass.Feature.Mean(12).MLP.PrecisionC2,Triclass.Feature.Mean(12).MLP.RecallC2,Triclass.Feature.Mean(12).MLP.F1C2] =  CM_Sen_Spec_trinary_calc(Triclass.Feature.Mean(12).Label,Triclass.Feature.Mean(12).MLP.Prediction,class)

[Triclass.Feature.Long(1).LSTM.AccuracyC2,Triclass.Feature.Long(1).LSTM.TPRC2,Triclass.Feature.Long(1).LSTM.PrecisionC2,Triclass.Feature.Long(1).LSTM.RecallC2,Triclass.Feature.Long(1).LSTM.F1C2] =  CM_Sen_Spec_trinary_calc(Triclass.Feature.Long(1).Label,Triclass.Feature.Long(1).LSTM.Prediction,class)
[Triclass.Feature.Long(5).LSTM.AccuracyC2,Triclass.Feature.Long(5).LSTM.TPRC2,Triclass.Feature.Long(5).LSTM.PrecisionC2,Triclass.Feature.Long(5).LSTM.RecallC2,Triclass.Feature.Long(5).LSTM.F1C2] =  CM_Sen_Spec_trinary_calc(Triclass.Feature.Long(5).Label,Triclass.Feature.Long(5).LSTM.Prediction,class)
[Triclass.Feature.Long(12).LSTM.AccuracyC2,Triclass.Feature.Long(12).LSTM.TPRC2,Triclass.Feature.Long(12).LSTM.PrecisionC2,Triclass.Feature.Long(12).LSTM.RecallC2,Triclass.Feature.Long(12).LSTM.F1C2] =  CM_Sen_Spec_trinary_calc(Triclass.Feature.Long(12).Label,Triclass.Feature.Long(12).LSTM.Prediction,class)
[Triclass.Feature.Mean(5).LSTM.AccuracyC2,Triclass.Feature.Mean(5).LSTM.TPRC2,Triclass.Feature.Mean(5).LSTM.PrecisionC2,Triclass.Feature.Mean(5).LSTM.RecallC2,Triclass.Feature.Mean(5).LSTM.F1C2] =  CM_Sen_Spec_trinary_calc(Triclass.Feature.Mean(5).Label,Triclass.Feature.Mean(5).LSTM.Prediction,class)
[Triclass.Feature.Mean(12).LSTM.AccuracyC2,Triclass.Feature.Mean(12).LSTM.TPRC2,Triclass.Feature.Mean(12).LSTM.PrecisionC2,Triclass.Feature.Mean(12).LSTM.RecallC2,Triclass.Feature.Mean(12).LSTM.F1C2] =  CM_Sen_Spec_trinary_calc(Triclass.Feature.Mean(12).Label,Triclass.Feature.Mean(12).LSTM.Prediction,class)


class =3

[Triclass.Feature.Long(1).CNN.AccuracyC3,Triclass.Feature.Long(1).CNN.TPRC3,Triclass.Feature.Long(1).CNN.PrecisionC3,Triclass.Feature.Long(1).CNN.RecallC3,Triclass.Feature.Long(1).CNN.F1C3] =  CM_Sen_Spec_trinary_calc(Triclass.Feature.Long(1).Label,Triclass.Feature.Long(1).CNN.Prediction,class)
[Triclass.Feature.Long(5).CNN.AccuracyC3,Triclass.Feature.Long(5).CNN.TPRC3,Triclass.Feature.Long(5).CNN.PrecisionC3,Triclass.Feature.Long(5).CNN.RecallC3,Triclass.Feature.Long(5).CNN.F1C3] =  CM_Sen_Spec_trinary_calc(Triclass.Feature.Long(5).Label,Triclass.Feature.Long(5).CNN.Prediction,class)
[Triclass.Feature.Long(12).CNN.AccuracyC3,Triclass.Feature.Long(12).CNN.TPRC3,Triclass.Feature.Long(12).CNN.PrecisionC3,Triclass.Feature.Long(12).CNN.RecallC3,Triclass.Feature.Long(12).CNN.F1C3] =  CM_Sen_Spec_trinary_calc(Triclass.Feature.Long(12).Label,Triclass.Feature.Long(12).CNN.Prediction,class)
[Triclass.Feature.Mean(5).CNN.AccuracyC3,Triclass.Feature.Mean(5).CNN.TPRC3,Triclass.Feature.Mean(5).CNN.PrecisionC3,Triclass.Feature.Mean(5).CNN.RecallC3,Triclass.Feature.Mean(5).CNN.F1C3] =  CM_Sen_Spec_trinary_calc(Triclass.Feature.Mean(5).Label,Triclass.Feature.Mean(5).CNN.Prediction,class)
[Triclass.Feature.Mean(12).CNN.AccuracyC3,Triclass.Feature.Mean(12).CNN.TPRC3,Triclass.Feature.Mean(12).CNN.PrecisionC3,Triclass.Feature.Mean(12).CNN.RecallC3,Triclass.Feature.Mean(12).CNN.F1C3] =  CM_Sen_Spec_trinary_calc(Triclass.Feature.Mean(12).Label,Triclass.Feature.Mean(12).CNN.Prediction,class)

[Triclass.Feature.Long(1).MLP.AccuracyC3,Triclass.Feature.Long(1).MLP.TPRC3,Triclass.Feature.Long(1).MLP.PrecisionC3,Triclass.Feature.Long(1).MLP.RecallC3,Triclass.Feature.Long(1).MLP.F1C3] =  CM_Sen_Spec_trinary_calc(Triclass.Feature.Long(1).Label,Triclass.Feature.Long(1).MLP.Prediction,class)
[Triclass.Feature.Long(5).MLP.AccuracyC3,Triclass.Feature.Long(5).MLP.TPRC3,Triclass.Feature.Long(5).MLP.PrecisionC3,Triclass.Feature.Long(5).MLP.RecallC3,Triclass.Feature.Long(5).MLP.F1C3] =  CM_Sen_Spec_trinary_calc(Triclass.Feature.Long(5).Label,Triclass.Feature.Long(5).MLP.Prediction,class)
[Triclass.Feature.Long(12).MLP.AccuracyC3,Triclass.Feature.Long(12).MLP.TPRC3,Triclass.Feature.Long(12).MLP.PrecisionC3,Triclass.Feature.Long(12).MLP.RecallC3,Triclass.Feature.Long(12).MLP.F1C3] =  CM_Sen_Spec_trinary_calc(Triclass.Feature.Long(12).Label,Triclass.Feature.Long(12).MLP.Prediction,class)
[Triclass.Feature.Mean(5).MLP.AccuracyC3,Triclass.Feature.Mean(5).MLP.TPRC3,Triclass.Feature.Mean(5).MLP.PrecisionC3,Triclass.Feature.Mean(5).MLP.RecallC3,Triclass.Feature.Mean(5).MLP.F1C3] =  CM_Sen_Spec_trinary_calc(Triclass.Feature.Mean(5).Label,Triclass.Feature.Mean(5).MLP.Prediction,class)
[Triclass.Feature.Mean(12).MLP.AccuracyC3,Triclass.Feature.Mean(12).MLP.TPRC3,Triclass.Feature.Mean(12).MLP.PrecisionC3,Triclass.Feature.Mean(12).MLP.RecallC3,Triclass.Feature.Mean(12).MLP.F1C3] =  CM_Sen_Spec_trinary_calc(Triclass.Feature.Mean(12).Label,Triclass.Feature.Mean(12).MLP.Prediction,class)

[Triclass.Feature.Long(1).LSTM.AccuracyC3,Triclass.Feature.Long(1).LSTM.TPRC3,Triclass.Feature.Long(1).LSTM.PrecisionC3,Triclass.Feature.Long(1).LSTM.RecallC3,Triclass.Feature.Long(1).LSTM.F1C3] =  CM_Sen_Spec_trinary_calc(Triclass.Feature.Long(1).Label,Triclass.Feature.Long(1).LSTM.Prediction,class)
[Triclass.Feature.Long(5).LSTM.AccuracyC3,Triclass.Feature.Long(5).LSTM.TPRC3,Triclass.Feature.Long(5).LSTM.PrecisionC3,Triclass.Feature.Long(5).LSTM.RecallC3,Triclass.Feature.Long(5).LSTM.F1C3] =  CM_Sen_Spec_trinary_calc(Triclass.Feature.Long(5).Label,Triclass.Feature.Long(5).LSTM.Prediction,class)
[Triclass.Feature.Long(12).LSTM.AccuracyC3,Triclass.Feature.Long(12).LSTM.TPRC3,Triclass.Feature.Long(12).LSTM.PrecisionC3,Triclass.Feature.Long(12).LSTM.RecallC3,Triclass.Feature.Long(12).LSTM.F1C3] =  CM_Sen_Spec_trinary_calc(Triclass.Feature.Long(12).Label,Triclass.Feature.Long(12).LSTM.Prediction,class)
[Triclass.Feature.Mean(5).LSTM.AccuracyC3,Triclass.Feature.Mean(5).LSTM.TPRC3,Triclass.Feature.Mean(5).LSTM.PrecisionC3,Triclass.Feature.Mean(5).LSTM.RecallC3,Triclass.Feature.Mean(5).LSTM.F1C3] =  CM_Sen_Spec_trinary_calc(Triclass.Feature.Mean(5).Label,Triclass.Feature.Mean(5).LSTM.Prediction,class)
[Triclass.Feature.Mean(12).LSTM.AccuracyC3,Triclass.Feature.Mean(12).LSTM.TPRC3,Triclass.Feature.Mean(12).LSTM.PrecisionC3,Triclass.Feature.Mean(12).LSTM.RecallC3,Triclass.Feature.Mean(12).LSTM.F1C3] =  CM_Sen_Spec_trinary_calc(Triclass.Feature.Mean(12).Label,Triclass.Feature.Mean(12).LSTM.Prediction,class)





class =1

[Triclass.Raw.Long(1).CNN.AccuracyC1,Triclass.Raw.Long(1).CNN.TPRC1,Triclass.Raw.Long(1).CNN.PrecisionC1,Triclass.Raw.Long(1).CNN.RecallC1,Triclass.Raw.Long(1).CNN.F1C1] =  CM_Sen_Spec_trinary_calc(Triclass.Raw.Long(1).Label,Triclass.Raw.Long(1).CNN.Prediction,class)
[Triclass.Raw.Long(5).CNN.AccuracyC1,Triclass.Raw.Long(5).CNN.TPRC1,Triclass.Raw.Long(5).CNN.PrecisionC1,Triclass.Raw.Long(5).CNN.RecallC1,Triclass.Raw.Long(5).CNN.F1C1] =  CM_Sen_Spec_trinary_calc(Triclass.Raw.Long(5).Label,Triclass.Raw.Long(5).CNN.Prediction,class)
[Triclass.Raw.Long(12).CNN.AccuracyC1,Triclass.Raw.Long(12).CNN.TPRC1,Triclass.Raw.Long(12).CNN.PrecisionC1,Triclass.Raw.Long(12).CNN.RecallC1,Triclass.Raw.Long(12).CNN.F1C1] =  CM_Sen_Spec_trinary_calc(Triclass.Raw.Long(12).Label,Triclass.Raw.Long(12).CNN.Prediction,class)
[Triclass.Raw.Mean(5).CNN.AccuracyC1,Triclass.Raw.Mean(5).CNN.TPRC1,Triclass.Raw.Mean(5).CNN.PrecisionC1,Triclass.Raw.Mean(5).CNN.RecallC1,Triclass.Raw.Mean(5).CNN.F1C1] =  CM_Sen_Spec_trinary_calc(Triclass.Raw.Mean(5).Label,Triclass.Raw.Mean(5).CNN.Prediction,class)
[Triclass.Raw.Mean(12).CNN.AccuracyC1,Triclass.Raw.Mean(12).CNN.TPRC1,Triclass.Raw.Mean(12).CNN.PrecisionC1,Triclass.Raw.Mean(12).CNN.RecallC1,Triclass.Raw.Mean(12).CNN.F1C1] =  CM_Sen_Spec_trinary_calc(Triclass.Raw.Mean(12).Label,Triclass.Raw.Mean(12).CNN.Prediction,class)

[Triclass.Raw.Long(1).MLP.AccuracyC1,Triclass.Raw.Long(1).MLP.TPRC1,Triclass.Raw.Long(1).MLP.PrecisionC1,Triclass.Raw.Long(1).MLP.RecallC1,Triclass.Raw.Long(1).MLP.F1C1] =  CM_Sen_Spec_trinary_calc(Triclass.Raw.Long(1).Label,Triclass.Raw.Long(1).MLP.Prediction,class)
[Triclass.Raw.Long(5).MLP.AccuracyC1,Triclass.Raw.Long(5).MLP.TPRC1,Triclass.Raw.Long(5).MLP.PrecisionC1,Triclass.Raw.Long(5).MLP.RecallC1,Triclass.Raw.Long(5).MLP.F1C1] =  CM_Sen_Spec_trinary_calc(Triclass.Raw.Long(5).Label,Triclass.Raw.Long(5).MLP.Prediction,class)
[Triclass.Raw.Long(12).MLP.AccuracyC1,Triclass.Raw.Long(12).MLP.TPRC1,Triclass.Raw.Long(12).MLP.PrecisionC1,Triclass.Raw.Long(12).MLP.RecallC1,Triclass.Raw.Long(12).MLP.F1C1] =  CM_Sen_Spec_trinary_calc(Triclass.Raw.Long(12).Label,Triclass.Raw.Long(12).MLP.Prediction,class)
[Triclass.Raw.Mean(5).MLP.AccuracyC1,Triclass.Raw.Mean(5).MLP.TPRC1,Triclass.Raw.Mean(5).MLP.PrecisionC1,Triclass.Raw.Mean(5).MLP.RecallC1,Triclass.Raw.Mean(5).MLP.F1C1] =  CM_Sen_Spec_trinary_calc(Triclass.Raw.Mean(5).Label,Triclass.Raw.Mean(5).MLP.Prediction,class)
[Triclass.Raw.Mean(12).MLP.AccuracyC1,Triclass.Raw.Mean(12).MLP.TPRC1,Triclass.Raw.Mean(12).MLP.PrecisionC1,Triclass.Raw.Mean(12).MLP.RecallC1,Triclass.Raw.Mean(12).MLP.F1C1] =  CM_Sen_Spec_trinary_calc(Triclass.Raw.Mean(12).Label,Triclass.Raw.Mean(12).MLP.Prediction,class)

[Triclass.Raw.Long(1).LSTM.AccuracyC1,Triclass.Raw.Long(1).LSTM.TPRC1,Triclass.Raw.Long(1).LSTM.PrecisionC1,Triclass.Raw.Long(1).LSTM.RecallC1,Triclass.Raw.Long(1).LSTM.F1C1] =  CM_Sen_Spec_trinary_calc(Triclass.Raw.Long(1).Label,Triclass.Raw.Long(1).LSTM.Prediction,class)
[Triclass.Raw.Long(5).LSTM.AccuracyC1,Triclass.Raw.Long(5).LSTM.TPRC1,Triclass.Raw.Long(5).LSTM.PrecisionC1,Triclass.Raw.Long(5).LSTM.RecallC1,Triclass.Raw.Long(5).LSTM.F1C1] =  CM_Sen_Spec_trinary_calc(Triclass.Raw.Long(5).Label,Triclass.Raw.Long(5).LSTM.Prediction,class)
% [Triclass.Raw.Long(12).LSTM.AccuracyC1,Triclass.Raw.Long(12).LSTM.TPRC1,Triclass.Raw.Long(12).LSTM.PrecisionC1,Triclass.Raw.Long(12).LSTM.RecallC1,Triclass.Raw.Long(12).LSTM.F1C1] =  CM_Sen_Spec_trinary_calc(Triclass.Raw.Long(12).Label,Triclass.Raw.Long(12).LSTM.Prediction,class)
[Triclass.Raw.Mean(5).LSTM.AccuracyC1,Triclass.Raw.Mean(5).LSTM.TPRC1,Triclass.Raw.Mean(5).LSTM.PrecisionC1,Triclass.Raw.Mean(5).LSTM.RecallC1,Triclass.Raw.Mean(5).LSTM.F1C1] =  CM_Sen_Spec_trinary_calc(Triclass.Raw.Mean(5).Label,Triclass.Raw.Mean(5).LSTM.Prediction,class)
[Triclass.Raw.Mean(12).LSTM.AccuracyC1,Triclass.Raw.Mean(12).LSTM.TPRC1,Triclass.Raw.Mean(12).LSTM.PrecisionC1,Triclass.Raw.Mean(12).LSTM.RecallC1,Triclass.Raw.Mean(12).LSTM.F1C1] =  CM_Sen_Spec_trinary_calc(Triclass.Raw.Mean(12).Label,Triclass.Raw.Mean(12).LSTM.Prediction,class)

class =2

[Triclass.Raw.Long(1).CNN.AccuracyC2,Triclass.Raw.Long(1).CNN.TPRC2,Triclass.Raw.Long(1).CNN.PrecisionC2,Triclass.Raw.Long(1).CNN.RecallC2,Triclass.Raw.Long(1).CNN.F1C2] =  CM_Sen_Spec_trinary_calc(Triclass.Raw.Long(1).Label,Triclass.Raw.Long(1).CNN.Prediction,class)
[Triclass.Raw.Long(5).CNN.AccuracyC2,Triclass.Raw.Long(5).CNN.TPRC2,Triclass.Raw.Long(5).CNN.PrecisionC2,Triclass.Raw.Long(5).CNN.RecallC2,Triclass.Raw.Long(5).CNN.F1C2] =  CM_Sen_Spec_trinary_calc(Triclass.Raw.Long(5).Label,Triclass.Raw.Long(5).CNN.Prediction,class)
[Triclass.Raw.Long(12).CNN.AccuracyC2,Triclass.Raw.Long(12).CNN.TPRC2,Triclass.Raw.Long(12).CNN.PrecisionC2,Triclass.Raw.Long(12).CNN.RecallC2,Triclass.Raw.Long(12).CNN.F1C2] =  CM_Sen_Spec_trinary_calc(Triclass.Raw.Long(12).Label,Triclass.Raw.Long(12).CNN.Prediction,class)
[Triclass.Raw.Mean(5).CNN.AccuracyC2,Triclass.Raw.Mean(5).CNN.TPRC2,Triclass.Raw.Mean(5).CNN.PrecisionC2,Triclass.Raw.Mean(5).CNN.RecallC2,Triclass.Raw.Mean(5).CNN.F1C2] =  CM_Sen_Spec_trinary_calc(Triclass.Raw.Mean(5).Label,Triclass.Raw.Mean(5).CNN.Prediction,class)
[Triclass.Raw.Mean(12).CNN.AccuracyC2,Triclass.Raw.Mean(12).CNN.TPRC2,Triclass.Raw.Mean(12).CNN.PrecisionC2,Triclass.Raw.Mean(12).CNN.RecallC2,Triclass.Raw.Mean(12).CNN.F1C2] =  CM_Sen_Spec_trinary_calc(Triclass.Raw.Mean(12).Label,Triclass.Raw.Mean(12).CNN.Prediction,class)

[Triclass.Raw.Long(1).MLP.AccuracyC2,Triclass.Raw.Long(1).MLP.TPRC2,Triclass.Raw.Long(1).MLP.PrecisionC2,Triclass.Raw.Long(1).MLP.RecallC2,Triclass.Raw.Long(1).MLP.F1C2] =  CM_Sen_Spec_trinary_calc(Triclass.Raw.Long(1).Label,Triclass.Raw.Long(1).MLP.Prediction,class)
[Triclass.Raw.Long(5).MLP.AccuracyC2,Triclass.Raw.Long(5).MLP.TPRC2,Triclass.Raw.Long(5).MLP.PrecisionC2,Triclass.Raw.Long(5).MLP.RecallC2,Triclass.Raw.Long(5).MLP.F1C2] =  CM_Sen_Spec_trinary_calc(Triclass.Raw.Long(5).Label,Triclass.Raw.Long(5).MLP.Prediction,class)
[Triclass.Raw.Long(12).MLP.AccuracyC2,Triclass.Raw.Long(12).MLP.TPRC2,Triclass.Raw.Long(12).MLP.PrecisionC2,Triclass.Raw.Long(12).MLP.RecallC2,Triclass.Raw.Long(12).MLP.F1C2] =  CM_Sen_Spec_trinary_calc(Triclass.Raw.Long(12).Label,Triclass.Raw.Long(12).MLP.Prediction,class)
[Triclass.Raw.Mean(5).MLP.AccuracyC2,Triclass.Raw.Mean(5).MLP.TPRC2,Triclass.Raw.Mean(5).MLP.PrecisionC2,Triclass.Raw.Mean(5).MLP.RecallC2,Triclass.Raw.Mean(5).MLP.F1C2] =  CM_Sen_Spec_trinary_calc(Triclass.Raw.Mean(5).Label,Triclass.Raw.Mean(5).MLP.Prediction,class)
[Triclass.Raw.Mean(12).MLP.AccuracyC2,Triclass.Raw.Mean(12).MLP.TPRC2,Triclass.Raw.Mean(12).MLP.PrecisionC2,Triclass.Raw.Mean(12).MLP.RecallC2,Triclass.Raw.Mean(12).MLP.F1C2] =  CM_Sen_Spec_trinary_calc(Triclass.Raw.Mean(12).Label,Triclass.Raw.Mean(12).MLP.Prediction,class)

[Triclass.Raw.Long(1).LSTM.AccuracyC2,Triclass.Raw.Long(1).LSTM.TPRC2,Triclass.Raw.Long(1).LSTM.PrecisionC2,Triclass.Raw.Long(1).LSTM.RecallC2,Triclass.Raw.Long(1).LSTM.F1C2] =  CM_Sen_Spec_trinary_calc(Triclass.Raw.Long(1).Label,Triclass.Raw.Long(1).LSTM.Prediction,class)
[Triclass.Raw.Long(5).LSTM.AccuracyC2,Triclass.Raw.Long(5).LSTM.TPRC2,Triclass.Raw.Long(5).LSTM.PrecisionC2,Triclass.Raw.Long(5).LSTM.RecallC2,Triclass.Raw.Long(5).LSTM.F1C2] =  CM_Sen_Spec_trinary_calc(Triclass.Raw.Long(5).Label,Triclass.Raw.Long(5).LSTM.Prediction,class)
% [Triclass.Raw.Long(12).LSTM.AccuracyC2,Triclass.Raw.Long(12).LSTM.TPRC2,Triclass.Raw.Long(12).LSTM.PrecisionC2,Triclass.Raw.Long(12).LSTM.RecallC2,Triclass.Raw.Long(12).LSTM.F1C2] =  CM_Sen_Spec_trinary_calc(Triclass.Raw.Long(12).Label,Triclass.Raw.Long(12).LSTM.Prediction,class)
[Triclass.Raw.Mean(5).LSTM.AccuracyC2,Triclass.Raw.Mean(5).LSTM.TPRC2,Triclass.Raw.Mean(5).LSTM.PrecisionC2,Triclass.Raw.Mean(5).LSTM.RecallC2,Triclass.Raw.Mean(5).LSTM.F1C2] =  CM_Sen_Spec_trinary_calc(Triclass.Raw.Mean(5).Label,Triclass.Raw.Mean(5).LSTM.Prediction,class)
[Triclass.Raw.Mean(12).LSTM.AccuracyC2,Triclass.Raw.Mean(12).LSTM.TPRC2,Triclass.Raw.Mean(12).LSTM.PrecisionC2,Triclass.Raw.Mean(12).LSTM.RecallC2,Triclass.Raw.Mean(12).LSTM.F1C2] =  CM_Sen_Spec_trinary_calc(Triclass.Raw.Mean(12).Label,Triclass.Raw.Mean(12).LSTM.Prediction,class)


class =3

[Triclass.Raw.Long(1).CNN.AccuracyC3,Triclass.Raw.Long(1).CNN.TPRC3,Triclass.Raw.Long(1).CNN.PrecisionC3,Triclass.Raw.Long(1).CNN.RecallC3,Triclass.Raw.Long(1).CNN.F1C3] =  CM_Sen_Spec_trinary_calc(Triclass.Raw.Long(1).Label,Triclass.Raw.Long(1).CNN.Prediction,class)
[Triclass.Raw.Long(5).CNN.AccuracyC3,Triclass.Raw.Long(5).CNN.TPRC3,Triclass.Raw.Long(5).CNN.PrecisionC3,Triclass.Raw.Long(5).CNN.RecallC3,Triclass.Raw.Long(5).CNN.F1C3] =  CM_Sen_Spec_trinary_calc(Triclass.Raw.Long(5).Label,Triclass.Raw.Long(5).CNN.Prediction,class)
[Triclass.Raw.Long(12).CNN.AccuracyC3,Triclass.Raw.Long(12).CNN.TPRC3,Triclass.Raw.Long(12).CNN.PrecisionC3,Triclass.Raw.Long(12).CNN.RecallC3,Triclass.Raw.Long(12).CNN.F1C3] =  CM_Sen_Spec_trinary_calc(Triclass.Raw.Long(12).Label,Triclass.Raw.Long(12).CNN.Prediction,class)
[Triclass.Raw.Mean(5).CNN.AccuracyC3,Triclass.Raw.Mean(5).CNN.TPRC3,Triclass.Raw.Mean(5).CNN.PrecisionC3,Triclass.Raw.Mean(5).CNN.RecallC3,Triclass.Raw.Mean(5).CNN.F1C3] =  CM_Sen_Spec_trinary_calc(Triclass.Raw.Mean(5).Label,Triclass.Raw.Mean(5).CNN.Prediction,class)
[Triclass.Raw.Mean(12).CNN.AccuracyC3,Triclass.Raw.Mean(12).CNN.TPRC3,Triclass.Raw.Mean(12).CNN.PrecisionC3,Triclass.Raw.Mean(12).CNN.RecallC3,Triclass.Raw.Mean(12).CNN.F1C3] =  CM_Sen_Spec_trinary_calc(Triclass.Raw.Mean(12).Label,Triclass.Raw.Mean(12).CNN.Prediction,class)

[Triclass.Raw.Long(1).MLP.AccuracyC3,Triclass.Raw.Long(1).MLP.TPRC3,Triclass.Raw.Long(1).MLP.PrecisionC3,Triclass.Raw.Long(1).MLP.RecallC3,Triclass.Raw.Long(1).MLP.F1C3] =  CM_Sen_Spec_trinary_calc(Triclass.Raw.Long(1).Label,Triclass.Raw.Long(1).MLP.Prediction,class)
[Triclass.Raw.Long(5).MLP.AccuracyC3,Triclass.Raw.Long(5).MLP.TPRC3,Triclass.Raw.Long(5).MLP.PrecisionC3,Triclass.Raw.Long(5).MLP.RecallC3,Triclass.Raw.Long(5).MLP.F1C3] =  CM_Sen_Spec_trinary_calc(Triclass.Raw.Long(5).Label,Triclass.Raw.Long(5).MLP.Prediction,class)
[Triclass.Raw.Long(12).MLP.AccuracyC3,Triclass.Raw.Long(12).MLP.TPRC3,Triclass.Raw.Long(12).MLP.PrecisionC3,Triclass.Raw.Long(12).MLP.RecallC3,Triclass.Raw.Long(12).MLP.F1C3] =  CM_Sen_Spec_trinary_calc(Triclass.Raw.Long(12).Label,Triclass.Raw.Long(12).MLP.Prediction,class)
[Triclass.Raw.Mean(5).MLP.AccuracyC3,Triclass.Raw.Mean(5).MLP.TPRC3,Triclass.Raw.Mean(5).MLP.PrecisionC3,Triclass.Raw.Mean(5).MLP.RecallC3,Triclass.Raw.Mean(5).MLP.F1C3] =  CM_Sen_Spec_trinary_calc(Triclass.Raw.Mean(5).Label,Triclass.Raw.Mean(5).MLP.Prediction,class)
[Triclass.Raw.Mean(12).MLP.AccuracyC3,Triclass.Raw.Mean(12).MLP.TPRC3,Triclass.Raw.Mean(12).MLP.PrecisionC3,Triclass.Raw.Mean(12).MLP.RecallC3,Triclass.Raw.Mean(12).MLP.F1C3] =  CM_Sen_Spec_trinary_calc(Triclass.Raw.Mean(12).Label,Triclass.Raw.Mean(12).MLP.Prediction,class)

[Triclass.Raw.Long(1).LSTM.AccuracyC3,Triclass.Raw.Long(1).LSTM.TPRC3,Triclass.Raw.Long(1).LSTM.PrecisionC3,Triclass.Raw.Long(1).LSTM.RecallC3,Triclass.Raw.Long(1).LSTM.F1C3] =  CM_Sen_Spec_trinary_calc(Triclass.Raw.Long(1).Label,Triclass.Raw.Long(1).LSTM.Prediction,class)
[Triclass.Raw.Long(5).LSTM.AccuracyC3,Triclass.Raw.Long(5).LSTM.TPRC3,Triclass.Raw.Long(5).LSTM.PrecisionC3,Triclass.Raw.Long(5).LSTM.RecallC3,Triclass.Raw.Long(5).LSTM.F1C3] =  CM_Sen_Spec_trinary_calc(Triclass.Raw.Long(5).Label,Triclass.Raw.Long(5).LSTM.Prediction,class)
% [Triclass.Raw.Long(12).LSTM.AccuracyC3,Triclass.Raw.Long(12).LSTM.TPRC3,Triclass.Raw.Long(12).LSTM.PrecisionC3,Triclass.Raw.Long(12).LSTM.RecallC3,Triclass.Raw.Long(12).LSTM.F1C3] =  CM_Sen_Spec_trinary_calc(Triclass.Raw.Long(12).Label,Triclass.Raw.Long(12).LSTM.Prediction,class)
[Triclass.Raw.Mean(5).LSTM.AccuracyC3,Triclass.Raw.Mean(5).LSTM.TPRC3,Triclass.Raw.Mean(5).LSTM.PrecisionC3,Triclass.Raw.Mean(5).LSTM.RecallC3,Triclass.Raw.Mean(5).LSTM.F1C3] =  CM_Sen_Spec_trinary_calc(Triclass.Raw.Mean(5).Label,Triclass.Raw.Mean(5).LSTM.Prediction,class)
[Triclass.Raw.Mean(12).LSTM.AccuracyC3,Triclass.Raw.Mean(12).LSTM.TPRC3,Triclass.Raw.Mean(12).LSTM.PrecisionC3,Triclass.Raw.Mean(12).LSTM.RecallC3,Triclass.Raw.Mean(12).LSTM.F1C3] =  CM_Sen_Spec_trinary_calc(Triclass.Raw.Mean(12).Label,Triclass.Raw.Mean(12).LSTM.Prediction,class)


